name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # to use node16 instead of node12 which is deprecated

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1 # Use the latest major version for stability
        with:
          cmake-version: '3.26.3'

      - name: Install dependencies
        run: sudo apt-get install -y libgtest-dev libgmock-dev

      - name: Configure CMake
        run: |
          rm -rf build
          mkdir build
          cd build
          cmake ..

      - name: Build Main Executable and Test Executable
        run: |
          cd build
          make

      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure
