name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # to use node20 instead of node12 and node 16 which are deprecated

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2 # Use the latest major version for stability
        with:
          cmake-version: '3.26.3'

      - name: Install dependencies
        run: sudo apt-get install -y libgtest-dev libgmock-dev

      - name: Configure CMake
        run: |
          rm -rf build
          mkdir build
          cd build
          cmake ..

      - name: Build Main Executable and Test Executable
        run: |
          cd build
          make

      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure
          - name: Analyze code with clang-tidy
          
      - name: Analyze code with clang-tidy
        run: |
          cd build
         make clang-tidy

      #- name: Check code formatting with clang-format
      #  run: |
      #    cd build
      #    make clang-format-check

      - name: Generate code coverage
        run: |
          cd build
          make coverage

      - name: Upload code coverage results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: coverage-results
          path: build/coverage-results


