name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1.10
        with:
          cmake-version: '3.19.3'

      - name: Install dependencies
        run: sudo apt-get install -y libgtest-dev

      - name: Configure CMake
        run: |
          mkdir -p build
          cd build
          cmake ..

      - name: Build Main Executable and Test Executable
        run: |
          cd build
          make

      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure
