name: Pull Request CI

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    name: Build & Run All Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      #- name: Cache CMake files
      #  uses: actions/cache@v3
      #  with:
      #    path: |
      #      build/CMakeFiles
      #      build/CMakeCache.txt
      #      build/compile_commands.json
      #    key: ${{ runner.os }}-cmake-build-${{ github.sha }}
      #    restore-keys: |
      #      ${{ runner.os }}-cmake-build-

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.26.3'

      - name: Install dependencies
        run: sudo apt-get install -y libgtest-dev libgmock-dev libboost-all-dev libeigen3-dev

      - name: Configure CMake
        run: |
          cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_CXX_STANDARD=20 ..

      - name: Build Main Executable and Test Executable
        run: |
          cmake --build build --target Unit_tests Integration_tests

      - name: Run all Tests
        run: |
          cd build
          ctest --output-on-failure
