name: Pull Request CI

on: # On what action this workflow will be triggered
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    name: Build & Run All Tests # Give the build job an appropriate name
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # to use node20 instead of node12 and node 16 which are deprecated

    #  - name: Cache CMake files
    #    uses: actions/cache@v3
    #    with:
    #      path: |
    #        build/CMakeFiles
    #        build/CMakeCache.txt
    #        build/compile_commands.json
    #      key: ${{ runner.os }}-cmake-build-${{ github.sha }}
    #      restore-keys: |
    #        ${{ runner.os }}-cmake-build-

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2 # Use the latest major version for stability
        with:
          cmake-version: '3.26.3'

      - name: Install dependencies
        run: sudo apt-get install -y libgtest-dev libgmock-dev libboost-all-dev libeigen3-dev

      - name: Configure CMake
        run: |
          cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_CXX_STANDARD=20 ..

      - name: Build Main Executable and Test Executable
        run: |
          cmake --build build --target Unit_tests Integration_tests

      - name: Run all Tests
        run: |
          cd build
          ctest --output-on-failure
